sudo: required
language: python
python:
- '3.7'
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
- curl https://cli-assets.heroku.com/install.sh | sh #new method
# login to docker registries (dockerhub + heroku) 
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
- docker login -u "$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com
script:
- docker-compose run --entrypoint="python manage.py test" web
- docker ps
- docker tag covid-19-predictive-analysis_web registry.heroku.com/covid-analysis-mformihir/web

deploy:
  provider: script
  script: 
    docker push registry.heroku.com/covid-analysis-mformihir/web;
    heroku container:release web --app covid-analysis-mformihir
    heroku run python3 manage.py migrate --app covid-analysis-mformihir
  app: covid-analysis-mformihir
  on:
    branch: heroku
    
