language: python
python:
- '3.7'
services:
- docker
before_install:
- docker-compose build
- docker-compose up -d
script:
- docker-compose run web python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: fqu5jSNd3FAqDFvreDhiSag8qGY/fnTuMnYKeIRFDeA8BN9+3NU9wvF7Zl149AMQXyC63czmbrO0cNprqaKWSW9wpxxbCCkseqTufVYcoOso7HjEoydhKj41Hb2uLN5BXD5mOC5SyH+itaEzots7Mr0S3Qr0kzT51J0s+7HGhfNjjqucdYrBQ6Us4ohr598qX8/ct4wrsV1luEz26so7yvKC99iPOnafeTfAEusKIYV2TtdeFSCP58ffqLRErLNrmneXNVd3nFRXnkCCjdLExAgcLYsabw2y179/L4ukMeGLTvXOGE+q3SkCNLALlcFh2vqwzF5SedDvFeEXkvKQeAVpv+o0VMiCH1RggFDx+FOugJccGyisqeG9PcTPvMMxg8RtYXL1+2zxWF57OML+7uSX31LVUM+GSk2OdrKawGjtVtUk+f8aYY26IX/901MnSLLCujcNU3m60X//EWxH3zN7YJ3ZeYwmitzZ9VPqrDw2MraH0kyGAe3Gfx0+Z3Omybg0lcGTMEY3k37rkgS80M0Bh1vQRKDc9Ix1594MOLyaMlpYtTXYvi70bHsEbDsGwqbKMMfx26LIqMK1xT7GRVd+Pz94/fyrvac6gqMyzmVyBK21Vzo9RUQ/ADEfd4Cj3cm+Tj4jS2F1/DLnTmWCXzAwwLsAKGEDH1j5+WW1s3w=
  app: covid-analysis-mformihir
  on: master
  run:
    - "docker-compose run web python manage.py migrate"
    - "docker-compose run web python manage.py runserver"
